@startuml

title __REPOSITORY's Class Diagram__\n

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.AmmonimentiRepository {
            {abstract} + findByFoto()
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.FotoRepository {
            {abstract} + findFotoById()
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.MatchRepository {
            {abstract} + findAllByStudente1AndStudente2()
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.NotificaRepository {
            {abstract} + findByUtenteAndEmailToMatchWith()
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.ProfiloRepository {
            {abstract} + findProfiloById()
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.SegnalazioniRepository {
            {abstract} + findByModeratoreAndFoto()
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.SospensioniRepository {
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.UtenteRepository {
            {abstract} + findAllByRuolo()
            {abstract} + findByEmail()
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Repository {
        interface com.unidates.Unidates.UniDates.Repository.VerificationTokenRepository {
            {abstract} + findByToken()
            {abstract} + findByUtente()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
