@startuml

title __ENUM's Class Diagram__\n

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Model {
        namespace Enum {
          enum Colore_Occhi {
            AMBRA
            AZZURRI
            CASTANI
            GRIGI
            NERI
            ROSSI
            VERDI
            occhi
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Model {
        namespace Enum {
          enum Colori_Capelli {
            ALTRO
            AMBRA
            BIONDI
            CASTANI
            GRIGI
            NERI
            ROSSI
            colore
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Model {
        namespace Enum {
          enum Hobby {
            ALTRO
            ANIME
            ARTE
            CALCIO
            CINEMA
            CUCINA
            DISEGNO
            FOTOGRAFIA
            FUMETTI
            INFORMATICA
            LIBRI
            MANGA
            MODA
            MOTORI
            MUSICA
            NATURA
            POLITICA
            SERIE_TV
            SPORT
            STORIA
            TEATRO
            TECNOLOGIA
            TV
            VIAGGI
            VIDEOGIOCHI
            topic
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Model {
        namespace Enum {
          enum Interessi {
            ALTRO
            DONNE
            ENTRAMBI
            UOMINI
            interessi
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Model {
        namespace Enum {
          enum Motivazione {
            CONETNUTO_NON_PERTINENTE
            CONTENUTO_OFFENSIVI
            NUDITA
            SPAM
            VIOLENZA
            motivazione
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Model {
        namespace Enum {
          enum Ruolo {
            COMMUNITY_MANAGER
            MODERATORE
            STUDENTE
            ruolo
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Model {
        namespace Enum {
          enum Sesso {
            ALTRO
            DONNA
            UOMO
            sesso
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.unidates.Unidates.UniDates {
      namespace Model {
        namespace Enum {
          enum Tipo_Notifica {
            AMMONIMENTO
            MATCH
            tipo_noitica
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
